name: Download Google Drive Folder

on:
  workflow_dispatch:
    inputs:
      folder_url:
        description: 'Google Drive Folder URL'
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install gdown
        sudo apt-get install unzip -y

    - name: Download Google Drive folder
      run: |
        gdown "${{ github.event.inputs.folder_url }}" -O ./gdrive-files --folder

    - name: Compress downloaded files
      run: |
        zip -r gdrive-files.zip gdrive-files

    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: google-drive-files
        path: gdrive-files.zip
        retention-days: 1
